### PR TITLE
AppNotFoundException

### LINKED ISSUE #60: GetApp should throw if the app is not found
`IAppDirectory.GetApp` should throw a specific error to be consistent with the AppD REST API that will return a 4XX error if the app is not found.

### PR DESCRIPTION
**Pull request by BalassaMarton**
Changed AppDirectory.GetApp to throw when the app is not found
Closes #60

### CODE REVIEW

File: src/Fdc3.AppDirectory/AppDirectoryExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    {
+        /// <summary>
+        /// Returns an application by appId from the AppDirectory, or <c>null</c> if the app is not found.
+        /// </summary>
+        /// <param name="appDirectory">The <see cref="IAppDirectory"/> instance</param>
+        /// <param name="appId">Application identifier</param>
+        /// <returns>The application or <c>null</c></returns>
+        public static async Task<Fdc3App?> TryGetApp(this IAppDirectory appDirectory, string appId)
+        {
+            try
```
Comment (ztanczos) [inline src/Fdc3.AppDirectory/AppDirectoryExtensions.cs:29]: I think it would be better to avoid the exception in a `TryGet*` method rather than catching it. Would that be possible?

Comment (BalassaMarton) [reply src/Fdc3.AppDirectory/AppDirectoryExtensions.cs:29]: The change is about throwing instead of returning `null` - which we can debate, see the linked issue. I don't feel strongly about it, I just noticed that the AppD REST API returns an error response when the app is not found.

Comment (ztanczos) [reply src/Fdc3.AppDirectory/AppDirectoryExtensions.cs:29]: Yeah I agree with the linked issue & the `Get*` part, my comment is just for the `TryGet*` method.

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance#try-parse-pattern
In my mind if I see an API which provides both a `Get*` and a `TryGet*` method my assumption is that the first one can throw an exception but the later won't. If the only way of implementing the `TryGet*` is by wrapping the `Get*` in a try-catch then I don't think it should be part of the API - the consumers can do that themselves and decide better what to do in the catch block.

Comment (BalassaMarton) [reply src/Fdc3.AppDirectory/AppDirectoryExtensions.cs:29]: This is a helper method in case you really just want to swallow the exception. `GetApp` shouldn't be called with arbitrary identifiers anyway. The most likely scenario when you would try to fetch the API with a nonexistent appId is when an app is removed from the AppD but some persisted layout tries to load it. I'm fine with removing this extension method altogether.

Comment (bingenito) [reply src/Fdc3.AppDirectory/AppDirectoryExtensions.cs:29]: Should we just suggest consumers use ContinueWith()?

Comment (BalassaMarton) [reply src/Fdc3.AppDirectory/AppDirectoryExtensions.cs:29]: Do you mean this?
```cs
appDirectory.GetApp(appId).ContinueWith(t => t.IsFaulted ? null : t.Result)
```
That's the same thing just with more boilerplate.

Comment (bingenito) [reply src/Fdc3.AppDirectory/AppDirectoryExtensions.cs:29]: I think the confusion is the Try* pattern is around returning a bool and out.  For this to work with TPL you will have a difficult tuple so just embrace using TPL.  Perhaps we split this one item out of the rest of the PR so the rest can merged.

Comment (BalassaMarton) [reply src/Fdc3.AppDirectory/AppDirectoryExtensions.cs]: Removed the extension.

File: src/Tests/MorganStanley.Fdc3.AppDirectory.Tests/MorganStanley.Fdc3.AppDirectory.Tests.csproj [hunk 2]
```diff
@@ -20,6 +20,7 @@
 
   <ItemGroup>
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
+    <PackageReference Include="Moq" Version="4.20.69" />
```
Comment (bingenito) [inline src/Tests/MorganStanley.Fdc3.AppDirectory.Tests/MorganStanley.Fdc3.AppDirectory.Tests.csproj:23]: Where is this being used?

Comment (BalassaMarton) [reply src/Tests/MorganStanley.Fdc3.AppDirectory.Tests/MorganStanley.Fdc3.AppDirectory.Tests.csproj]: Nowhere indeed, removed.

**Review by bingenito — APPROVED** [review]
